import re, json, collections
from queries import no, SKIP, clean
# ordered (regex on lowercase title) -> canonical Commons search; None = skip
RULES = [
 (r'scalil|scalett|scalini|scalille', None), (r'^cucullo|^easter bread|panettone', None),
 (r'garlic bread', 'garlic bread'), (r'bruschetta', 'bruschetta'), (r'muffa', 'muffuletta'), (r'turnover', 'savory turnover'),
 (r'bread bowl', 'bread bowl dip'), (r'roll.?ups|roll-ups', 'tortilla pinwheels'), (r'vegetable sandwich', None), (r'russian sandwich', None),
 (r'brie', 'baked brie'), (r'cheese ball|cheese log', 'cheese ball'), (r'nacho|mexican dip|salsa dip', 'nachos'), (r'crostini', 'crostini'),
 (r'parmesan balls', 'fried cheese balls'), (r'croquette', 'croquettes'), (r'party pork balls', 'cocktail meatballs'), (r'crab dip|creamy crab', 'crab dip'),
 (r'salmon ball|salmon dip', 'salmon spread'), (r'tuna dill', 'tuna canapes'), (r'artichoke.*dip|spinach and artichoke', 'spinach artichoke dip'), (r'hummus', 'hummus'),
 (r'onion soup dip|cottage cheese dip', 'sour cream dip'),
 (r'daiquiri', 'daiquiri cocktail'), (r'martini', 'martini cocktail'), (r'sidecar', 'sidecar cocktail'), (r'singapore sling', 'singapore sling'), (r'negroni', 'negroni'),
 (r'americano', 'americano cocktail'), (r'milano torino', 'milano torino cocktail'), (r'planters', "planter's punch"), (r'mimosa', 'mimosa cocktail'),
 (r'champagne rose', 'champagne punch'), (r'christmas punch|tropical punch', 'fruit punch'), (r'mocha frapp', 'frappe coffee'), (r'morning shake', 'smoothie'),
 (r'hot cranberry|apple tea toddy', 'hot toddy'),
 (r'stracciatella', 'stracciatella soup'), (r'wedding soup', 'italian wedding soup'), (r'tortellini soup', 'tortellini soup'), (r'chicken soup|meat broth|goulash broth', 'chicken soup'),
 (r'bouillabaisse|fish soup|fish tomato sauce soup|zuppa di pesce', 'fish soup'), (r'barley soup', 'barley soup'), (r'kielbasa soup|pasulj|bean soup', 'bean soup'),
 (r'pasta e fagioli|pasta and fagioli', 'pasta e fagioli'), (r'pasta e ceci', 'pasta e ceci'), (r'cauliflo', 'cauliflower soup'), (r'leek potato', 'leek and potato soup'),
 (r'lentil|lenticchie', 'lentil soup'), (r'minestrone', 'minestrone'), (r'french onion', 'french onion soup'), (r'peas and rice|split pea', 'split pea soup'),
 (r'potato soup', 'baked potato soup'), (r'borsch', 'borscht'), (r'spinach and rice soup', 'spinach soup'), (r'vegetarian soup', 'vegetable soup'), (r'butternut', 'butternut squash soup'),
 (r'orange and fennel', 'orange fennel salad'), (r'raspberry.spinach', 'spinach strawberry salad'), (r'waldorf', 'waldorf salad'), (r'pasta salad|pasta toss', 'pasta salad'),
 (r'rice and .*salad|rice salad', 'rice salad'), (r'crab salad|crab and shrimp salad', 'crab salad'), (r'seafood salad', 'seafood salad'), (r'bean salad|tuna and bean', 'bean salad'),
 (r'beet.*salad', 'beet salad'), (r'caesar', 'caesar salad'), (r'caprese', 'caprese salad'), (r'cauliflower salad', 'cauliflower salad'), (r'chicken salad', 'chicken salad'),
 (r'coleslaw|napa cabbage salad', 'coleslaw'), (r'olive salad', 'olive salad'), (r'potato.*salad|potatoes and greenbeans', 'potato salad'), (r'romaine salad', 'romaine salad'),
 (r'artichoke', 'stuffed artichokes'), (r'asparagus$|roasted asparagus', 'roasted asparagus'), (r'beans with sage|green beans|serbian beans', 'green beans'), (r'bok choy', 'bok choy'),
 (r'broccoli.*(bake|stew)', 'broccoli casserole'), (r'brussel', 'roasted brussels sprouts'), (r'cabbage rolls|holubts', 'cabbage rolls'), (r'fried cabbage|saut.ed cabbage', 'fried cabbage'),
 (r'carrots', 'glazed carrots'), (r'cauliflower (gratin|frittelli)', 'cauliflower gratin'), (r'cipollini', 'cipollini onions'), (r'corn on the cob', 'corn on the cob'),
 (r'caponata', 'caponata'), (r'eggplant (rollatini|rolls)|rollatini', 'eggplant rollatini'), (r'eggplant lasagna', 'eggplant parmigiana'), (r'stuffed.*eggplant', 'stuffed eggplant'),
 (r'eggplant', 'eggplant dish'), (r'mushrooms$|saut.ed mushrooms', 'sauteed mushrooms'), (r'onion rings', 'onion rings'), (r'ajvar', 'ajvar'), (r'stuffed peppers', 'stuffed peppers'),
 (r'twice baked', 'twice baked potatoes'), (r'boiled potatoes', 'boiled potatoes'), (r'mashed potatoes', 'mashed potatoes'), (r'potato mold|gatto', 'gattò di patate'),
 (r'potatoes and mushrooms|scalloped potatoes|cheese tater', 'scalloped potatoes'), (r'roasted potatoes', 'roasted potatoes'), (r'sweet potato', 'sweet potato casserole'),
 (r'rapini', 'broccoli rabe'), (r'spinach cheese casserole', 'spinach casserole'), (r'squash', 'spaghetti squash'), (r'swiss chard', 'swiss chard'), (r'rice stuffed tomatoes', 'stuffed tomatoes'),
 (r'turnip', 'turnip'), (r'ratatouille|vegetable medley|marinated vegetables|stuffed vegetables', 'ratatouille'), (r'zucchini flower|pitolini', 'fried zucchini flowers'),
 (r'fried zucchini|zucchini milanese', 'fried zucchini'), (r'zucchini ricotta lasagna|zucchini lasagna', 'zucchini lasagna'),
 (r'giardiniera', 'giardiniera'), (r'olives', 'olives'), (r'roasted.*red peppers|roasted canned', 'roasted red peppers'), (r'bean canning', 'canned green beans'), (r'chestnuts', 'roasted chestnuts'),
 (r'figs', 'figs'), (r'roasted pears', 'roasted pears goat cheese'), (r'covered strawberries', 'chocolate covered strawberries'),
 (r'fried rice', 'fried rice'), (r'suppli', 'suppli'), (r'wild rice', 'wild rice casserole'), (r'mushroom rice', 'mushroom rice'), (r'risotto lasagna', None),
 (r'porcini|wild mushrooms', 'mushroom risotto'), (r'asparagus risotto|asparagus tips', 'asparagus risotto'), (r'milanese', 'risotto alla milanese'), (r'radicchio', 'radicchio risotto'),
 (r'seafood risotto|risotto al seafood|squid|shrimp.*risotto|bean risotto', 'seafood risotto'), (r'sun-dried tomato risotto', 'risotto'),
 (r'dumplings|pelmeni|vareniki|perogi|pyrohy', 'pierogi'), (r'fresh pasta|pasta fresca', 'fresh pasta'), (r'quick cook sauce|fresh tomato sauce|marinara|spaghetti sauce|meat sauce|carne al sugo', 'tomato sauce spaghetti'),
 (r'bolognese', 'spaghetti bolognese'), (r'beef and spaghetti', 'spaghetti with meat sauce'), (r'tex mex|chicken vegetable pasta|chicken noodle', 'chicken pasta'),
 (r'amatriciana', 'bucatini all\'amatriciana'), (r'carbonara|papalina|eggs and bacon', 'spaghetti carbonara'), (r'gricia|pancetta & chick|bacon, mushrooms', 'pasta guanciale'),
 (r'pesto', 'pesto'), (r'vodka', 'penne alla vodka'), (r'cauliflower sauce|broccoli, mushrooms', 'pasta with cauliflower'), (r'ham bone|peas or bean|green bean sauce', 'pasta with beans'),
 (r'eggplant pasta', 'pasta alla norma'), (r'aio e oio|garlic & oil|garlic and pepper', 'spaghetti aglio e olio'), (r'fusilli', 'fusilli pasta'), (r'boscaiola', 'pasta with mushrooms'),
 (r'pasta e patate|potatoes & pasta', 'pasta e patate'), (r'primavera|spring penne', 'pasta primavera'), (r'arrabbiata', 'penne all\'arrabbiata'), (r'sun-dried', 'penne with sun-dried tomatoes'),
 (r'alfredo', 'fettuccine alfredo'), (r'bocconcini|summer pasta', 'caprese pasta'), (r'cream & lemon|cream and tomato', 'pasta cream sauce'), (r'macaroni and cheese', 'macaroni and cheese'),
 (r'romano cheese|cacio', 'cacio e pepe'), (r'ricotta & zucchini|philly pesto', 'pasta zucchini'), (r'rigatoni', 'rigatoni'), (r'stuffed pasta shells', 'stuffed shells'),
 (r'putanesca|puttanesca', 'spaghetti alla puttanesca'), (r'baccala.*sauce', 'baccalà'), (r'clam', 'linguine alle vongole'), (r'salmon pasta|salmon & shrimp|seafood sauce|shrimp alla vodka|tagliolini|squid tomato|tuna fish tomato|pasta con tonno', 'seafood pasta'),
 (r'cannelloni|canneloni|crepes crespelle', 'cannelloni'), (r'gnocchi', 'gnocchi'), (r'lasagna|al forno', 'lasagna'), (r'manicotti', 'manicotti'), (r'polenta|corn bread|corn meal', 'polenta'),
 (r'ravioli', 'ravioli'), (r'perogies', 'pierogi'),
 (r'liver', 'liver and onions'), (r'tripe', 'trippa'), (r'osso ?buco', 'osso buco'), (r'meatballs', 'meatballs'), (r'hamburgers|pljeskavica', 'hamburger'), (r'meat ?loaf', 'meatloaf'),
 (r'sausage|cevapcici|kielbasa', 'sausages'), (r'sloppy joes', 'sloppy joe'), (r'stroganoff', 'beef stroganoff'), (r'burek', 'burek'), (r'beef strips|stir fried beef', 'beef stir fry'),
 (r'beef stew|bourguignon', 'beef stew'), (r'noodle bowl', 'noodle bowl'), (r'roast beef|prime rib|pot roast|beef tenderloin|round steak', 'roast beef'),
 (r'veal chops', 'veal chop'), (r'milanese veal|veal milanese', 'cotoletta alla milanese'), (r'veal cutlet|veal scallop|chicken/veal|cutlets', 'veal cutlet'), (r'veal lemon|piccata', 'veal piccata'), (r'saltimbocca', 'saltimbocca'),
 (r'ham$|celebration ham|orange ham', 'baked ham'), (r'pork and broccoli|pork tenderloin slices', 'pork stir fry'), (r'pork.*(roast|loin|shoulder|tenderloin)|rack of pork|porchetta', 'roast pork'),
 (r'kebob|kabob', 'kebab'), (r'pork chops', 'pork chops'), (r'ribs', 'pork ribs'), (r'goulash|pork stew|muckalica|pork dinner', 'goulash'), (r'pigs in a blanket', 'pigs in a blanket'),
 (r'sausages and onions', 'sausage and onions'), (r'pork & beans|pork and beans', 'pork and beans'), (r'hot dogs', 'hot dog'), (r'capicollo|prosciuttini|cured pork', 'capicollo'),
 (r'lamb chops|lamb loin|shoulder chops|sweet and sour chops', 'lamb chops'), (r'lamb curry', 'lamb curry'), (r'lamb kabob', 'lamb kebab'), (r'leg of lamb', 'roast leg of lamb'),
 (r'rack of lamb', 'rack of lamb'), (r'lamb shank|lamb shoulder|lamb fricassee|hot pot|lamb.*stir', 'braised lamb'), (r'rabbit', 'rabbit stew'),
 (r'stuffed roast chickens|drunken chicken|beer can', 'roast chicken'), (r'chicken breast', 'chicken breast'), (r'divan', 'chicken divan'), (r'florentine', 'chicken florentine'),
 (r'marsala', 'chicken marsala'), (r'parmesan chicken|chicken parmesan', 'chicken parmesan'), (r'cacciatore|cacciatora', 'chicken cacciatore'), (r'stir fry', 'chicken stir fry'),
 (r'paella', 'paella'), (r'stuffed chicken', 'stuffed chicken breast'), (r'drumsticks|thighs', 'chicken drumsticks'), (r'wings', 'chicken wings'), (r'gizzard', None), (r'duck', 'duck a l\'orange'),
 (r'turkey chili', 'turkey chili'), (r'turkey', 'roast turkey'), (r'chicken', 'chicken dish'), (r'barbecue|bar-be-que|bbq', 'barbecue'),
 (r'fish', 'fried fish'), (r'baccala', 'baccalà'), (r'calamari', 'fried calamari'), (r'crustaceans', 'seafood stew'), (r'clams', 'steamed clams'), (r'crab cakes', 'crab cakes'), (r'crab legs', 'crab legs'),
 (r'lobster', 'lobster tail'), (r'mussels', 'mussels marinara'), (r'salmon', 'salmon fillet'), (r'hollandaise', 'hollandaise sauce'), (r'scallop|st\. jacques', 'scallops'), (r'shrimp', 'shrimp'),
 (r'smelt', 'fried smelt'), (r'snails', 'snails'), (r'sole', 'sole fillet'), (r'squid', 'squid'), (r'trout', 'trout'),
 (r'eggs benedict', 'eggs benedict'), (r'boiled eggs', 'boiled eggs'), (r'over easy|sunny side', 'fried egg'), (r'poached', 'poached egg'), (r'purgatory', 'eggs in purgatory'), (r'egg salad', 'egg salad'),
 (r'scrambled', 'scrambled eggs'), (r'omelette|omelet', 'omelette'), (r'frittata', 'frittata'), (r'gibanica|cheese pie|moussaka|quiche', 'quiche'),
 (r'french bread', 'french bread'), (r'whole-wheat|bread in a pan|yeast bread|italian bread', 'bread loaf'), (r'bread balls|dinner rolls', 'bread rolls'), (r'bird buns|briosche|brioche', 'brioche'),
 (r'pogaca', 'pogača'), (r'pumpernickel', 'pumpernickel bread'), (r'povotica', 'povitica'), (r'coffee loaves|coffee braid|coffee ring|houska|walnut roll', 'sweet bread'), (r'crumpets', 'crumpets'),
 (r'taralle 2001|taralle', 'taralli'), (r'pizza dough|pizza freeze|white pizza|topping', 'pizza dough'), (r'pizza with|fried pizza|pizza$', 'pizza'), (r'roulade|stuffed rolled', 'stromboli'), (r'calzone', 'calzone'),
 (r'enchilada', 'enchiladas'), (r'focaccia', 'focaccia'), (r'spring rolls', 'spring rolls'), (r'tacos', 'tacos'), (r'tortillas', 'chicken tortilla wrap'),
 (r'almond (biscotti|apricot)|biscotti di mandorle|almond cranberry|italian almond|raffalini|almond imma', 'cantucci'), (r'biscotti', 'biscotti'), (r'amaretti', 'amaretti'),
 (r'almond (cookies|crescents|loaves|slices|orange)|crescent|arrotolati', 'almond crescent cookies'), (r'peach', 'pesche dolci'), (r'pizzelle', 'pizzelle'),
 (r'chocolate chip', 'chocolate chip cookies'), (r'chocolate.*cookies|chocolate kisses', 'chocolate cookies'), (r'coffee.*cookies', 'coffee cookies'), (r'funghi|mushroom cookies', 'mushroom cookies'),
 (r'lemon.*(cookies|sables)', 'lemon cookies'), (r'macaroons|meringues', 'macaroons'), (r'oatmeal.*(cookies|monster)', 'oatmeal cookies'), (r'oatmeal snowball', 'snowball cookies'),
 (r'orange.*cookies|orange juice cookies', 'orange cookies'), (r'ricotta cookies', 'ricotta cookies'), (r'mexican wedding|snowball', 'snowball cookies'), (r'savoiardi', 'ladyfingers'),
 (r'shortbread', 'shortbread'), (r'snickerdoodle', 'snickerdoodle'), (r'sugar cookies', 'sugar cookies'), (r'thimble', 'thumbprint cookies'), (r'toll house', 'chocolate chip cookies'),
 (r'torcetti', 'torcetti'), (r'refrigerator cookies|vanilla cookies|butter cookies|sour cream cookies|special .k. cookies|german cookies|honey cookies|granola|molasses|mincemeat cookies|pineapple cookies|mocha nut|cookie', 'cookies'),
 (r'donuts|doughnuts', 'doughnuts'), (r'cristate', 'cristoli'), (r'zeppol', 'zeppole'), (r'apple crisp|oatmeal crisp', 'apple crisp'), (r'chocolate pudding', 'chocolate pudding'), (r'bread pudding', 'bread pudding'),
 (r'pear pudding', 'pear dessert'), (r'rice pudding', 'rice pudding'), (r'brownies', 'brownies'), (r'lemon (squares|bars)', 'lemon bars'), (r'nanaimo', 'nanaimo bars'),
 (r'rice krispies', 'rice krispies treats'), (r'butterscotch squares', 'butterscotch bars'), (r'squares|orange nut bars|raisin bars|pumpkin spice bars', 'dessert bars'),
 (r'apple.*cake|apple or blueberry', 'apple cake'), (r'banana', 'banana bread'), (r'carrot cake', 'carrot cake'), (r'chocolate.*(cake|cupcakes)', 'chocolate cake'), (r'coffee cake', 'coffee cake'),
 (r'bundt|proja', 'bundt cake'), (r'date and nut', 'date nut bread'), (r'panna cotta', 'panna cotta'), (r'brack', 'barmbrack'), (r'lemon.*cake', 'lemon cake'), (r'meringue', 'meringue torte'),
 (r'nut bread|nut loaf|orange.*(loaf|bread)|zucchini bread|pumpkin.*bread|pumpkin tea cake', 'quick bread loaf'), (r'oreo', 'oreo cake'), (r'pound cake', 'pound cake'), (r'peanut butter cake', 'peanut butter cake'),
 (r'poppy seed cake', 'poppy seed cake'), (r'ricotta cake', 'ricotta cake'), (r'shortcake', 'strawberry shortcake'), (r'sponge|pane di spagna', 'sponge cake'), (r'spice cake', 'spice cake'),
 (r'zucchini cake|sour cream cake|mocha oatmeal cake|halloween pumpkin cake|mocha chocolate cake', 'cake slice'), (r'tiramisu', 'tiramisu'),
 (r'pumpkin.*(pie|torte)', 'pumpkin pie'), (r'asparagus rolls', 'asparagus rolls'), (r'butter tarts|banbury', 'butter tarts'), (r'mille', 'mille-feuille'), (r'cream puffs', 'cream puffs'),
 (r'almond bark|chocolate torrone|torrone', 'torrone'), (r'rum balls|pecan balls|sweet maries', 'rum balls'), (r'bavarian|rum cream pie|cream pie', 'cream pie'), (r'fruit tarts|shortbread tarts', 'fruit tart'),
 (r'ice cream cake', 'ice cream cake'), (r'clusters|peanuts|marshmallow', 'peanut clusters'), (r'rocky road', 'rocky road'), (r'souffle', 'lemon souffle'), (r'trifle', 'trifle'), (r'truffles', 'chocolate truffles'),
 (r'cheese ?cake', 'cheesecake'), (r'pistacchio', 'pistachio dessert'), (r'walnut cream crescent', 'crescent rolls'), (r'apple pie', 'apple pie'), (r'peach pie', 'peach pie'), (r'pear tart', 'pear tart'),
 (r'ricotta pie|crostata', 'crostata di ricotta'), (r'pancakes?', 'pancakes'), (r'french toast', 'french toast'), (r'crepes|palacinke', 'crepes'), (r'biscuits', 'buttermilk biscuits'), (r'scones', 'scones'),
 (r'muffins', 'muffins'), (r'blueberry cake', 'blueberry cake'), (r'christmas|vanilla biscuits', 'christmas cookies'), (r'gingerbread', 'gingerbread'), (r'fiadone', None),
]
RULES = [(re.compile(a), b) for a, b in RULES]
def group_for(x):
    t = x['title'].strip().lower()
    if SKIP.match(t): return None
    for rx, q in RULES:
        if rx.search(t): return q
    return clean(x['title'])
if __name__ == '__main__':
    g = collections.defaultdict(list)
    for x in no: g[group_for(x)].append(x['title'])
    none = g.pop(None, [])
    print(len(no), 'recipes ->', len(g), 'queries; skipped', len(none))
    import sys
    loose = {k: v for k, v in g.items() if len(v) == 1 and not any(k == r[1] for r in RULES)}
    print('unmatched (default cleaned):', ' | '.join(sorted(f"{v[0]}=>{k}" for k, v in loose.items())))
